### ISSUE TITLE
Update profile info

### ISSUE THREAD

**Issue by timsayshey** [ErikKalkoken/slackApiDoc#1]
In the documentation you say it requires scope:?? 
https://github.com/ErikKalkoken/slackApiDoc/blob/master/users.profile.set.md

What scope do I actually need to make this work?

I keep getting the following response when trying this:
{"ok":false,"error":"invalid_auth","warning":"superfluous_charset"}

And I have permissions for the following scopes:
users:read,users:write

**Comment by ErikKalkoken** [comment]
nice work! care to add that to the docu?

**Comment by timsayshey** [comment]
Pull request submitted :)
