### ISSUE TITLE
`channel_not_found` error from `users.admin.invite` endpoint

### ISSUE THREAD

**Issue by ollieh-m** [ErikKalkoken/slackApiDoc#12]
I got a `channel_not_found` error until I used the channel `ID`, rather than the channel `name`, in the list of channels a user should be auto-enrolled. I'm not sure if that's because it was a private channel, so am raising an issue rather than submitting a PR. Others might benefiting from being aware that they may need to use the ID, not the channel name.

**Comment by ErikKalkoken** [comment]
Thanks for raising the issue. The channel name worked before, so that might actually be a change to the API. Would be great if you could make a pull request to reflect the change.

**Comment by ErikKalkoken** [comment]
The correctly specifies that only IDs work.
