### ISSUE TITLE
Always got invalid_email when i try invite new member

### ISSUE THREAD

**Issue by bizlevel** [ErikKalkoken/slackApiDoc#18]
I use invite new member and on any email i got error "invalid_email"!

{"ok":false,"error":"invalid_email"}

For example:
TOKEN=XXXXXXXXXXX
curl -X GET https://slack.com/api/users.admin.invite?email=root@mydomain.com&token=$TOKEN
#curl -X GET https://slack.com/api/users.admin.invite?token=$TOKEN&email=root@mydomain.com

But other is works
curl -s -X GET https://slack.com/api/channels.list?token=$TOKEN  | jq '.' > channels.json

What is wrong?

**Comment by ErikKalkoken** [comment]
yes, some emails do not work he API. In that case you will have to invite manually.
Its a case I have also seen (although rarely). Since this is an undocumented API there is not much one can do about it unfortunately.

**Comment by Kopertje** [comment]
Hi there! I got the same error when doing a POST and with a standard Gmail email address.
Is there any progress on this api call by Slack? Or are there any other ways to automate the creation of slack users?

**Comment by ErikKalkoken** [comment]
No, there is no progress on this particular API and I am afraid you can not expect any. This API endpoint is undocumented and the Slack team will not provide any support for it or make improvements. All support requests regarding undocumented endpoints are denied (I tried).

Yes, there is also the [SCIM API,](https://api.slack.com/scim#post-users) which you can use to create users programmatically. However, the SCIM API is available to workspaces on the plus plan or Enterprise Grid only.
