### ISSUE TITLE
Active users after deactivating by users.admin.setInactive

### ISSUE THREAD

**Issue by kosmail3r** [ErikKalkoken/slackApiDoc#21]
Hello!
When user baceme to be deactivated (after using method users.admin.setInactive), is there any possibilities to active him using slackAPI?

**Comment by ErikKalkoken** [comment]
I don't know and since these methods only work for paid tier I have no way of testing. I would suggest asking this question on https://stackoverflow.com/. The Slack community is pretty active there.
