### ISSUE TITLE
can a bot user use the chat.command method?

### ISSUE THREAD

**Issue by wen830722** [ErikKalkoken/slackApiDoc#22]
I tried chat.command method with Slack **bot** token, but got an error of "missing_scope".
The token needed "post" scope. However, official documents show that "post" scope is deprecated. How can I make my BOT token have "post" scope?

**Comment by ErikKalkoken** [comment]
You are correct that the undocumented chat.command requires the post scope to work, which is not available in the standard OAuth process (e.g. you can not choose it as scope on the Slack app config site.)

The only currently working solution that I know of it to use a legacy token.

See also my answer on [stackoverflow](https://stackoverflow.com/a/45586027/4379151) to the same question.

But I agree that this is an important function that should work with the standard Oauth process. I will contact Slack support about this. Maybe they can be persuaded to add one of the current scopes to this method.
