### ISSUE TITLE
files.unshare

### ISSUE THREAD

**Issue by gunar** [ErikKalkoken/slackApiDoc#23]
The browser seems to be able to send API calls to `files.unshare`.
You might want to add that info to this repo.

**Comment by ErikKalkoken** [comment]
Interesting. Do you maybe have some more info about, e.g. what parameters, scopes?

**Comment by gunar** [comment]
Same arguments as `files.share`. 
Similarly, seems to require a scope named [post](https://api.slack.com/scopes/post) which the app can not request.

**Comment by gunar** [comment]
Reponse
```json
{ ok: true,             
  scopes: [ 'identify', 'read', 'post', 'client', 'apps', 'admin' ],
  acceptedScopes: [ 'post' ] }                  
```

**Comment by ErikKalkoken** [comment]
I tested it, but can not get it to work using a full admin legacy token. `files.share` works, but `files.unshare` does not with the same token. I get the below error message. This API method may be restricted to use by the Slack main app itself. Or did you get it to work somehow?
```

    {
        ok : false,
        error : "not_allowed_token_type"
    }
```

**Comment by gunar** [comment]
Forgot to mention I've used the Browser Token.

**Comment by ErikKalkoken** [comment]
I see. OK, then you can not really use this API method, so I don't think its makes sense to document it here.

**Comment by gunar** [comment]
Of couse you can (as much as you would any other undocumented endpoint). You just need a browser token, that's all.

**Comment by ErikKalkoken** [comment]
Technically you are correct, but I don't see how a Slack app, which is usually running on a web server get the browser token. Or do you have a solution? And how would that work for multiple Slack teams using that Slack app?

**Comment by gunar** [comment]
Grab it from your browser cookies. Agree that there is no way to make it programmatically work for multiple Slack teams, but that does not mean this endpoint should not be documented here.

Is Slack Endpoint :white_check_mark:
Is Undocumented :white_check_mark:
