### ISSUE TITLE
How Send Channels in users.admin.invite?

### ISSUE THREAD

**Issue by duraiganesh0** [ErikKalkoken/slackApiDoc#31]
i dont know how to send the channels parameter in **users.admin.invite**.
i'm currently sending the channels as a list like this
`channels = ["C8687"]`
and got this response `{'ok': False, 'error': 'channel_not_found'}`
How to send this paramter. FYI i'm using slack_client package in python.

**Comment by ErikKalkoken** [comment]
It depends how your `channels` variable is later combined into the http query to Slack. In general you need to send the list of channel IDs as http query parameter. 
Example:
`https://slack.com/api/users.admin.invite?token=TOKEN&email=abc@xyz,com&channels=C1234567890,G12345678`

**Comment by duraiganesh0** [comment]
i'm currently sending like this.
sc = SlackClient("xoxp-3434545-565656-2342342-2gb5h6y66")
def invite_user(name,email):
  resp = sc.api_call(
    "users.admin.invite",
    first_name=name,
    email=email,
    channels='C4GHT66',
    resend=True,
    validate=True,
  )
  print(resp)

is this correct?
