### ISSUE TITLE
Is this still working?

### ISSUE THREAD

**Issue by jmayhew-oc** [ErikKalkoken/slackApiDoc#37]
We have a new slack account and can't seem to get channels.delete to work. It returns:

```
{
    "ok": false,
    "error": "missing_scope",
    "needed": "post",
    "provided": "admin,identify,commands,incoming-webhook,channels:history,mpim:history,channels:read,mpim:read,users:read,channels:write,mpim:write,users:write,users.profile:write"
}
```

**Comment by ErikKalkoken** [comment]
Yes it does. And you need to provide a legacy token. Its the only one that has the "post" scope. 
https://api.slack.com/custom-integrations/legacy-tokens
