### ISSUE TITLE
users.admin.invite optional params don't work

### ISSUE THREAD

**Issue by Yankovsky** [ErikKalkoken/slackApiDoc#40]
I've tried channels, first_name and last_name params from doc, but they don't work. User still need to enter full name and display name on registration screen and after registration user has only one default channel.
Probably slack team changed something.

**Comment by Yankovsky** [comment]
Btw, thanks for your work!

**Comment by ErikKalkoken** [comment]
Nope, I can confirm that those API parameters still work. Nothing has changed.

I tested the channels, the first_name and last_name parameter and they work as documented. e.g. the new user auto-joined all specified additional channels.

So if it does not work for you, the root cause must lie somewhere else.

**Comment by ErikKalkoken** [comment]
Btw. if you like to get help with your code please post your issue on https://stackoverflow.com/. I will be happy to help you there get your code running.

**Comment by Yankovsky** [comment]
@ErikKalkoken hmm, ok, I'll try to make them work. Thank you!

**Comment by Yankovsky** [comment]
Ok, I found the problem. First call to method saves additional data about invited user. If you don't specify first_name, last_name or channels on first call, and then send another request with that data, it will be ignored.

**Comment by ErikKalkoken** [comment]
yes, good point. you can send an invite to an email address only once. Unless you remote the invite again before the recipient uses the link. then you can sent it again.

Maybe something to add to the documentation...

**Comment by soichih** [comment]
I've been trying to set first_name / last_name but I can't seem to get it to work.. Are you sure this is still working?

**Comment by ErikKalkoken** [comment]
You are right. those indeed seam not to work anymore.  But I just found out that `real_name` works and is not yet documented. I will update the API doc.

Thanks for letting me know!

**Comment by soichih** [comment]
Thanks. real_name works! May I ask how you are knowing this?

**Comment by ErikKalkoken** [comment]
I just use https://getnada.com/ to generate new emails and then try it out with my private workspace.
I guessed real_name was the one, because that is how its also called in the user object.
