### ISSUE TITLE
users.admin.invite - API error 

### ISSUE THREAD

**Issue by sanjaykumar2338** [ErikKalkoken/slackApiDoc#41]
Hi,

I am getting this error while using this API.

Error: {"ok":false,"error":"no_perms"}

I am sending a test token, email and channel name properly.

The error does not list  API error log documentation.

I use this WordPress plugin https://www.wpslacksync.com/.

Although I also trying to hit the API with token, email and channel directly in the browser HTTP. Same error encounter Error: {"ok":false,"error":"no_perms"}

Thanks

**Comment by ErikKalkoken** [comment]
Could be related to the role of your user. Please double-check that the user that is creating the legacy token has the admin or owner role. It will not work for "normal" users.
