### ISSUE TITLE
[question] missing_scope error in chat.command

### ISSUE THREAD

**Issue by vfiset** [ErikKalkoken/slackApiDoc#43]
Hi, regarding the [chat.command](https://github.com/ErikKalkoken/slackApiDoc/blob/master/chat.command.md), are you aware if there is a way to create a legacy token for a app/bot user ? I seem to be only able to create it for my personal user...

**Comment by ErikKalkoken** [comment]
Yes and sadly there is other way to use this and other undocumented API commands then with a Legacy token.
