### ISSUE TITLE
commands.list to get available slash commands

### ISSUE THREAD

**Issue by twouters** [ErikKalkoken/slackApiDoc#45]
Just noticed a commands.list request being used by Slack:

```
:method: POST
:path: /api/commands.list?_x_id=<someid>
```

As far as I can tell it returns a list of all available slash commands on our team

**Comment by twouters** [comment]
There seems to be a `commands_changed` event on RTM too, not sure what exaclty it returns though.

**Comment by ErikKalkoken** [comment]
Thanks for letting me know about this new undocumented slash command. It works great with legacy tokens and I have added it to the repo.

https://github.com/ErikKalkoken/slackApiDoc/blob/master/commands.list.md
