### ISSUE TITLE
https://github.com/ErikKalkoken/slackApiDoc/blob/master/users.admin.setInactive.md

### ISSUE THREAD

**Issue by loeken** [ErikKalkoken/slackApiDoc#46]
I am getting a "The command 'users.admin.setInactive' is not currently supported" returned from this endpoint, is there a new endpoint we should use instead for deactivating users?

**Comment by iamgeef** [comment]
I've just tried it on an account using the Standard plan and it still worked.

**Comment by ErikKalkoken** [comment]
@iamgeef Thank you for testing it.  I will close this issue based on your result.
