### ISSUE TITLE
Missing error - expiration_requires_restricted

### ISSUE THREAD

**Issue by thetwopct** [ErikKalkoken/slackApiDoc#48]
I'm trying to set invite expiry time via 

`expiration_ts `

but getting error 

`expiration_requires_restricted`

I'm guessing setting invite expiration is not available for free accounts?

**Comment by amancevice** [comment]
I think it’s saying you also have to provide channel(s) to restrict the user to

**Comment by ErikKalkoken** [comment]
I think `expiration_ts` only works together with `restricted` = `true`, so only with guest accounts. Which indeed are not available on Slack teams running on the free tier.
