### ISSUE TITLE
Another missing error in users.admin.invite

### ISSUE THREAD

**Issue by zxlin** [ErikKalkoken/slackApiDoc#53]
I just got a `already_in_team_invited_user` error from `users.admin.invite` which sounds really strange, like what does this even mean...? 

The user shows up as a "Full Member" on the Slack admin. So I guess it's more similar to `already_in_team` error.

**Comment by ErikKalkoken** [comment]
thanks for reporting the error. I can add it, but do you have any hint what the specific reason for that error occurring could be?

**Comment by zxlin** [comment]
I do not, unfortunately. I haven't been able to reproduce this error

**Comment by ErikKalkoken** [comment]
ok. I will add it anyways. maybe someone else can help us find more info for it.
