### ISSUE TITLE
conversations.convertToPrivate Method

### ISSUE THREAD

**Issue by iancward** [ErikKalkoken/slackApiDoc#54]
I'm looking into a way to programmatically convert a public channel to private (in order to make something self-service for end users) and it looks like the undocumented `conversations.convertToPrivate` API method is what the browser calls in order to make a channel private.

It looks like the browser client sends `token` and `channel` values through form data in a POST call.

**Comment by ErikKalkoken** [comment]
Hey. since your issue has nothing to do with any of the documented API endpoints in this repo, I will need to close it. 

To find and answer to your issue I would suggest to open a question on https://stackoverflow.com/questions/tagged/slack-api instead.

**Comment by iancward** [comment]
I'm not sure I understand; isn't this repository to document Slack's undocumented APIs?

I was asking if `conversations.convertToPrivate` could be added to the repository, as it is not documented by Slack.

**Comment by ErikKalkoken** [comment]
I am sorry, did indeed misunderstand your issue. 

however, after looking into this method it seams like it only works with runtime tokens. Those kind of endpoint are out-of-scope of this repo. Please see readme for details.

If you find a ways to work with this method using a user or legacy token feel free to open a new issue.
