### ISSUE TITLE
missing_scope 

### ISSUE THREAD

**Issue by juuuuuuuuuuuuuu** [ErikKalkoken/slackApiDoc#56]
I created slack app. and send slack app token.
but response is missing_scope.
this api is only use legacy token??
so user legacy token is only use???
how to send message poll using slack app.
please help me.

**Comment by jtatum** [comment]
This is mentioned in the readme.
>Slack apps: Since the post scope is not available through the standard Oauth process they can not be directly used in a normal Slack app. In order to use them in a Slack app a legacy token for the respective workspace needs to always be manually create and added.

**Comment by Avinesh** [comment]
@jtatum, but the legacy token which is created for a workspace will be used only by user. How to use the legacy token from a slack app?

**Comment by ErikKalkoken** [comment]
I think it is clearly stated:
> they can not be directly used in a normal Slack app

**Comment by ErikKalkoken** [comment]
I agree that this is very unfortunate, especially with the legacy tokens now being removed from Slack. The only other solution is to ask the Slack team for adding this feature to the normal methods. (which I already did btw). The more people requests this, the more likely it is to be included.
