### ISSUE TITLE
is users.admin.invite still valid?

### ISSUE THREAD

**Issue by jacobzlogar** [ErikKalkoken/slackApiDoc#59]
Sending requests with a legacy token for my user on a workspace I created, and with an email value i still always receive:
```
{
  "ok": false
  "error": "invalid_array_arg"
}
```

**Comment by ErikKalkoken** [comment]
Yes. Tested it just now and it still works.

Maybe your issue is related to this? 
https://stackoverflow.com/questions/35755165/slackbot-attachment-is-something-wrong-with-this
