### ISSUE TITLE
Removal of users.admin.invite

### ISSUE THREAD

**Issue by kittsville** [ErikKalkoken/slackApiDoc#65]
Are you aware of any alternatives to `users.admin.invite`? With the deprecation of legacy tokens the only endpoint publicly listed is `admin.users.invite`, which is Pro/Enterprise only.

The Slack web UI uses the `users.admin.inviteBulk` endpoint, which might be a viable alternative. Example payload:
```json
[{"email":"kittsville3@gmail.com","mode":"manual","type":"regular"}]
```

I would investigate this endpoint, but you're much more experienced at exploring undocumented Slack APIs than me.

**Comment by ErikKalkoken** [comment]
Sorry, but I am not aware of any alternative endpoint for this important feature.

But I think there is another alternative you can use: Invitation URLs. Instead of calling the endpoint, which is basically sending and email containing an invitation link to the provided email address, you can just do that yourself now.

**Comment by kittsville** [comment]
Unfortunately the invitation links now have an expiry date, max 30 days. It's possible this is only a UI limitation and you can get one that never expires from the API, but I haven't investigated yet.

I'm concerned this is a deliberate attempt to start getting rid of free communities.

**Comment by ErikKalkoken** [comment]
I just double-checked and I can create new invitation links that never expire. However, according to the docu they will expire after 2.000 invites.

Yeah, it is unfortunate. This will lead more people to use other products, e.g. many I know have switched to Discord.

**Comment by ErikKalkoken** [comment]
I put this info also on Stackoverflow: https://stackoverflow.com/questions/30955818/slack-api-team-invitation/63647218#63647218
