### ISSUE TITLE
Error when using API

### ISSUE THREAD

**Issue by twarner776** [ErikKalkoken/slackApiDoc#7]
![screen shot 2016-12-16 at 9 02 19 am](https://cloud.githubusercontent.com/assets/19413445/21265215/672e9a88-c36e-11e6-899f-b4e4b3c87142.png)
When using the API https://slack.com/api/users.admin.invite?token=token&email=email address&channels=channel id I am getting a error not allowed.  I would think that this is still working since the repo was updated 22 days ago but wanted to be sure I am not missing anything.

Thanks!

**Comment by ErikKalkoken** [comment]
Hey! yes, the invite method still works fine. I just tested it again to be sure. It looks like the access token you are using does not have the required rights to execute this method. The associated user needs to be admin.

**Comment by twarner776** [comment]
He Erik, I am doing this as a admin.  Below are the errors I am getting when testing in postman

As a admin I am getting the below

 {
  "ok": false,
  "error": "not_allowed"
}

If I change the user to a member the error changes to the below so I assume the permissions were right

{
  "ok": false,
  "error": "no_perms"
}

**Comment by ErikKalkoken** [comment]
Hi, sorry, but I have never encountered this error, so I am only guessing here. Two ideas though:

1) Could it be that this function has been disabled for your team? 
The same error message only exists for [files.sharedPublicURL]( https://api.slack.com/methods/files.sharedPublicURL). There it meant that the function has been disabled for the whole team. I don't think that you can turn off invitation for the free version of Slack, but if you are on a pair tier this option might exists

2) Are you sure you are using a user token and not a bot token? 
Bots are limited in what methods they can use. Usually that shield the error message "user_is_bot", but it might be different in this case.

Hope that helps a bit.

**Comment by hot-Whiskey** [comment]
@ErikKalkoken can you pass a groups parameter here or only channels?

**Comment by Malet** [comment]
I'm also having this issue, invites are disabled unless you're admin I've just using POST and GET:

```
+ curl -v 'https://<snip>.slack.com/api/users.admin.invite?email=test%40example.com&channels=C<snip>&token=<snip>'
*   Trying 52.X.X.X...
* Connected to <snip>.slack.com (127.0.0.1) port 443 (#0)
* TLS 1.2 connection using TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
* Server certificate: *.slack.com
* Server certificate: GeoTrust SSL CA - G3
* Server certificate: GeoTrust Global CA
> GET /api/users.admin.invite?email=test%40example.com&channels=C<snip>&token=<snip> HTTP/1.1
> Host: <snip>.slack.com
> User-Agent: curl/7.43.0
> Accept: */*
>
< HTTP/1.1 200 OK
< Content-Type: application/json; charset=utf-8
< Content-Length: 34
< Connection: keep-alive
< Access-Control-Allow-Origin: *
< Cache-Control: private, no-cache, no-store, must-revalidate
< Date: Thu, 20 Apr 2017 09:57:43 GMT
< Expires: Mon, 26 Jul 1997 05:00:00 GMT
< Pragma: no-cache
< Referrer-Policy: no-referrer
< Server: Apache
< Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
< Vary: Accept-Encoding
< X-Accepted-OAuth-Scopes: client
< X-Content-Type-Options: nosniff
< X-OAuth-Scopes: read,client,admin,identify,post,apps
< X-Slack-Backend: h
< X-Slack-Req-Id: 406e7d13-c014-47cd-bdb1-740cc7e17a9e
< X-XSS-Protection: 0
< X-Cache: Miss from cloudfront
< Via: 1.1 adc13b6f5827d04caa2efba65479257c.cloudfront.net (CloudFront)
< X-Amz-Cf-Id: xLSp6173T9YxrvNZeeI-Ql66RFK8fvU29bfWg7t-0bBCnSI7wj67yw==
<
* Connection #0 to host <snip>.slack.com left intact
{"ok":false,"error":"not_allowed"}
```

**Comment by fefe** [comment]
If SSO is enabled, you can't invite normal users, only guests. Hence the error -> `not_allowed`
You need an extra parameter to define that you are inviting guests.
Multi-channel guest: `restricted=1`
Single-channel guest: `ultra_restricted=1`

**Comment by ErikKalkoken** [comment]
Added the explanation and solution regarding the `not allowed` error to the documentation. Thank you @fefe for your contribution!
